# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef6d57882339170313b94e48bbbca3c157e1a16e83231f2e8c7b58afbb158bd52f58b58d5f20b7b30ded0ce64f831cb43e1a2b94c52bbf76940231afb6e57579

test:
  secret_key_base: a437be36d2af97c6c46d83b8d2ab5166e04f9b7259d79a583b8e87ad0d37e9506921f833eb2440427193bab85d077225aba9f0ac5febe8b11b4c521617c8e2ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
